
ALTER TABLE public.bot_config 
  ADD COLUMN IF NOT EXISTS trade_mode TEXT DEFAULT 'fixed',
  ADD COLUMN IF NOT EXISTS trade_percent NUMERIC DEFAULT 5,
  ADD COLUMN IF NOT EXISTS trade_min_usd NUMERIC DEFAULT 2,
  ADD COLUMN IF NOT EXISTS interval TEXT DEFAULT '1h';
