// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnblpyfbdjepmbcyocif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuYmxweWZiZGplcG1iY3lvY2lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5MjY5NTUsImV4cCI6MjA4NDUwMjk1NX0.2kE4qkInWYQfPrwjuBvH8x-COhO75uxD38WYybhfyrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});